Don't use None for type=string
It causes an exception since the charm doesn't have a condition to
handle None properly:

  File "templates/cinder_huawei_conf.xml", line 24, in <module>
    {% set initiators = options.iscsiinitiators.split(';') %}
jinja2.exceptions.UndefinedError: 'None' has no attribute 'split'

Closes: gh-7